[package]
name = "iphlpapi"
version = "0.0.1"
authors = ["adumbidiot <nathaniel.daniel23@outlook.com>"]
edition = "2018"

[dependencies]
iphlpapi-sys = { path = "./lib/iphlpapi-sys" }
winapi = { version = "0.3.8", features = [ "winerror" ] }

[workspace]
members = [ "./lib/iphlpapi-sys" ]